#!/usr/bin/env bash

bin/phosim.py validation/validation_3C_00_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_20_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_01_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_21_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_02_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_22_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_03_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_23_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_04_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_24_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_05_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_25_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_06_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_26_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_07_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_27_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_08_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_28_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_09_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_29_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_10_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_30_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_11_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_31_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_12_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_32_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_13_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"
bin/phosim.py validation/validation_3C_33_catalog -c validation/validation_3C_commands -s R22_S11 -e 0 "$@"


